### ISSUE TITLE
/s issues

### ISSUE THREAD

**Issue by jackrosenthal** [ColoradoSchoolOfMines/mozzarella#56]
* ``/s`` without a survey id fails with 500 (should be 404)
* ``/s`` with something that cannot be an integer fails (e.g., ``/s/foo``)... should be 404
* short urls for surveys are really pointless... I think our original thoughts would be that it would be easier to write on a white board, but we always use ``/attend`` anyway. Thoughts on changing this to ``/survey``?

**Comment by sumnerevans** [comment]
Have you changed your mind: https://github.com/ColoradoSchoolOfMines/mozzarella/issues/40#issuecomment-358561009? If we change this, we should change all usages of short URLs to maintain consistency.

**Comment by jackrosenthal** [comment]
No, I haven't changed my mind, and it's still consistent if we remove it.

Short URLs are for things that need to be quickly remembered or conveyed, for example, consider my personal homepage URL: http://inside.mines.edu/~jrosenth

The tilde notation is certainly not long, but it is easy to remember the path to my homepage and easy to type it as well.

Survey URLs are never "remembered" nor typed manually, therefore they do not need the short URLs.

**Comment by sumnerevans** [comment]
Ok. I'm fine with changing to `/survey` instead, then.

**Comment by liamwarfield** [comment]
created a branch with fixes called survey-Bugs

**Comment by samsartor** [comment]
I just noticed this change enter `develop`. I don't think we should have changed the survey endpoint. I originally chose it to be short so that we could easily email survey links, not because I planned on people remembering them. It is also more consistent with all the other short URLs we have.

**Comment by jackrosenthal** [comment]
If it's ``/s``, please use a textual identifier rather than a numeric id. The numeric id only makes sense if you are the application developer or the database.

**Comment by jackrosenthal** [comment]
::

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tg/_compat.py", line 87, in reraise
        raise value
      File "/usr/local/lib/python3.5/dist-packages/tg/appwrappers/transaction_manager.py", line 79, in __call__
        response = self.next_handler(controller, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/appwrappers/caching.py", line 54, in __call__
        return self.next_handler(controller, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/appwrappers/session.py", line 71, in __call__
        response = self.next_handler(controller, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/appwrappers/identity.py", line 47, in __call__
        return self.next_handler(controller, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/appwrappers/i18n.py", line 71, in __call__
        return self.next_handler(controller, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/wsgiapp.py", line 285, in _dispatch
        return controller(environ, context)
      File "/srv/acm/site/acmwebsite/lib/base.py", line 27, in __call__
        return TGController.__call__(self, environ, context)
      File "/usr/local/lib/python3.5/dist-packages/tg/controllers/dispatcher.py", line 119, in __call__
        response = self._perform_call(context)
      File "/usr/local/lib/python3.5/dist-packages/tg/controllers/dispatcher.py", line 99, in _perform_call
        state = self._get_dispatchable(context, py_request.quoted_path_info)
      File "/usr/local/lib/python3.5/dist-packages/tg/controllers/dispatcher.py", line 73, in _get_dispatchable
        state = state.resolve()
      File "/usr/local/lib/python3.5/dist-packages/crank/dispatchstate.py", line 178, in resolve
        return self._root_dispatcher._dispatch(self, self._path)
      File "/usr/local/lib/python3.5/dist-packages/crank/objectdispatcher.py", line 178, in _dispatch
        state, current_args)
      File "/usr/local/lib/python3.5/dist-packages/crank/objectdispatcher.py", line 103, in _dispatch_controller
        return dispatcher(state, remainder)
      File "/usr/local/lib/python3.5/dist-packages/crank/objectdispatcher.py", line 160, in _dispatch
        return self._dispatch_first_found_default_or_lookup(state, remainder)
      File "/usr/local/lib/python3.5/dist-packages/crank/objectdispatcher.py", line 129, in _dispatch_first_found_default_or_lookup
        new_controller, new_remainder = meth(*m_remainder)
    TypeError: _lookup() missing 1 required positional argument: 'sid'
